Update template-sync.yml

diff --git a/.github/workflows/template-sync.yml b/.github/workflows/template-sync.yml
--- a/.github/workflows/template-sync.yml
+++ b/.github/workflows/template-sync.yml
@@ -1,12 +1,20 @@
+name: Template sync
 on:
   # schedule:
   # - cron:  "0 0 1 * *"
   # manual trigger
   workflow_dispatch:
+
+
+env:
+  UPDATE_BRANCH: update-from-template
+  REMOTE_URL: https://github.com/kevinschaul/jump-start-template.git
+  REMOTE_BRANCH: gh-pages
   
 jobs:
-  repo-sync:
+  template-sync:
     runs-on: ubuntu-latest
+    
     permissions:
       contents: write
       pull-requests: write
@@ -16,9 +24,57 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: gh-pages
-      - uses: kota65535/github-template-sync-action@v1
+
+      # https://github.com/litetex/pull-detached-remote/blob/develop/alternative.yml
+      - name: Update from template
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          
+          echo "Adding remote template-repo"
+          git remote add template ${{ env.REMOTE_URL }}
+          
+          echo "Fetching remote template repo"
+          git fetch template
+          
+          echo "Deleting local branch that will contain the updates - if present"
+          git branch -D ${{ env.UPDATE_BRANCH }} || true
+          
+          echo "Checking if the remote template repo has new commits"
+          git rev-list ..template/${{ env.REMOTE_BRANCH }}
+
+          if [ $(git rev-list --count ..template/${{ env.REMOTE_BRANCH }}) -eq 0 ]; then
+            echo "There are no commits new commits on the template repo"
+            
+            echo "Deleting origin branch that contains the updates - if present"
+            git push -f origin --delete ${{ env.UPDATE_BRANCH }} || true
+            
+            echo "abort=1" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          
+          echo "Found new commits on the template repo"
+          
+          echo "Creating update branch"
+          git branch ${{ env.UPDATE_BRANCH }} template/${{ env.REMOTE_BRANCH }}
+          git branch --unset-upstream ${{ env.UPDATE_BRANCH }}
+          
+          echo "Pushing update branch"
+          git push -f -u origin ${{ env.UPDATE_BRANCH }}
+          
+          echo "Getting current branch"
+          current_branch=$(git branch --show-current)
+          echo "Current branch is $current_branch"
+          echo "current_branch=$current_branch" >> $GITHUB_OUTPUT
+
+          echo "abort=0" >> $GITHUB_OUTPUT          
+
+      - name: pull-request
+        uses: repo-sync/pull-request@v2
+        if: steps.main.outputs.abort == 0
         with:
-          template: kevinschaul/jump-start
-          template-branch: gh-pages
-          pr-base-branch: gh-pages
-          pr-title: Sync latest jump-start website
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          source_branch: ${{ env.UPDATE_BRANCH }}
+          destination_branch: ${{ steps.main.outputs.current_branch }}
+          pr_title: "Update from template"
+          pr_body: "An automated PR to sync changes from the template into this repo"
